spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show-sql: true
    properties:
      hibernate:
#        generate_statistics: true
        format_sql: true
  security:
    user:
      name: user
      password: 1234
      roles:
        - USER
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        security:
          web: trace
---
spring:
  config:
    activate:
      on-profile: deploy
server:
  port: 3000




