spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:myapp-test;
    driver-class-name: org.h2.Driver
    username: sa
    password:
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: deploy
server:
  port: 3000




